---
# defaults file for pxe
packages:
  - tftpd-hpa # serves pxeboot menu, files, vmlinuz, etc
  - nginx     # serves ISOs
  - syslinux 
  - pxelinux 
  - nfs-common # mounting nfs share

directories:
  # contains pxelinux configurations
  - /srv/tftp/pxelinux.cfg
  # contains vmlinuz, initrd, etc
  - /srv/tftp/images
  # files served by NGINX (e.g. ISOs)
  - /srv/http

# IP Address or DNS for PXE Server (tftp, nginx)
pxe_server_addr: "192.168.1.4"
# The path on the PXE server to mount 'nfs_server_share_path'
pxe_nfs_share_path: "/srv/http/images"
# The path to copy vmlinuz, initrd, etc
pxe_tftp_boot_path: "/srv/tftp/images"

# IP Address or DNS for NFS Server (images/isos)
nfs_server_addr: "192.168.1.5"
# The NFS Server Share to mount locally to PXE Server
nfs_server_share_path: "/share/images"

# default pxelinux installed files to copy and serve via tftp
pxelinux_files_served_by_tftp:
  - /usr/lib/PXELINUX/pxelinux.0
  - /usr/lib/syslinux/modules/bios/ldlinux.c32
  - /usr/lib/syslinux/modules/bios/menu.c32
  - /usr/lib/syslinux/modules/bios/libutil.c32
