---

# TODO: chown as tftp user
- name: copy pxeboot file to tftp serve directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/srv/tftp/{{ item | basename }}"
    owner: tftp
    group: tftp
    remote_src: true
  #loop: "{{ ipxe_files_served_by_tftp + grub_files_served_by_tftp }}"
  #loop: "{{ pxelinux_uefi_files_served_by_tftp }}"
  loop: "{{ pxelinux_bios_files_served_by_tftp }}"

- name: create pxe default menu
  ansible.builtin.template:
    src: pxelinux.cfg/default
    dest: "/srv/tftp/pxelinux.cfg/default"
    owner: tftp
    group: tftp

- name: update tftpd defaults
  ansible.builtin.lineinfile:
    path: /etc/default/tftpd-hpa
    regexp: '^TFTP_OPTIONS='
    line: TFTP_OPTIONS="--secure --verbose"
  notify:
    - restart tftpd

- name: create nginx images route
  ansible.builtin.template:
    src: nginx/images
    dest: /etc/nginx/sites-available/images

- name: enable nginx images route
  ansible.builtin.file:
    src: /etc/nginx/sites-available/images
    dest: /etc/nginx/sites-enabled/images
    state: link
  notify: reload nginx