---

# Mount NFS Mount NAS Server images directory to PXE Server
- name: mount nfs image volume
  ansible.posix.mount:
    src: "{{ nfs_server_addr }}:{{ nfs_server_share_path }}"
    path: "{{ pxe_nfs_share_path }}"
    opts: rw,sync,hard
    boot: false
    state: mounted
    fstype: nfs


- name: extract boot disk files from mounted isos
  ansible.builtin.script:
    cmd: scripts/extract-boot-disk.sh {{ pxe_nfs_share_path }} {{ pxe_tftp_boot_path }}
  register: result
  changed_when: '"true" in result.stdout_lines' # NOTE: script prints 'true' to stdout when changes occur