#!/bin/bash -e

###
# Generates base configurations for a Talos Cluster
###

# Consts
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/lib/consts.sh

mkdir -p $WORKER_OUTPUT_DIR
mkdir -p $PATCHES_DIR

usage() { echo "Usage: $0 [-n <name>] [-e <endpoint>] [-c <cluster>] [-k <kubernetes-version>]" 1>&2; exit 1; }

function generate_controller() {
  if [[ ! -f $SECRETS_FILE ]]; then
    # sanity baked into this command, requires --force to overwrite an existing secrets file.
    echo "creating: ${SECRETS_FILE}"
    talosctl gen secrets -o $SECRETS_FILE 2>/dev/null
  fi

  # Generate Controlplane 
  # NOTE: when multiple output types are selected, the output path must be a directory.. this prevents naming the controlplane.yaml file
  echo "creating: $OUTPUT_DIR/$NODE_NAME.yaml"
  talosctl gen config \
    --with-secrets="$SECRETS_FILE" \
    --with-docs=false \
    --with-examples=false \
    --kubernetes-version=$KUBERNETES_VERSION \
    --output-types controlplane \
    --config-patch-control-plane @${STRATEGIC_PATCH} \
    --config-patch-control-plane @${FIREWALL_TEMPLATE} \
    --output ${OUTPUT_DIR}/${NODE_NAME}.yaml \
    $EXTRA_ARGS \
    $CLUSTER_NAME \
    https://$ENDPOINT:6443

  if [[ ! -f $TALOSCONFIG_FILE ]]; then
    echo "creating: ${TALOSCONFIG_FILE}"
    # Generate Talosconfig
    talosctl gen config \
      --with-secrets="$SECRETS_FILE" \
      --with-docs=false \
      --with-examples=false \
      --output-types talosconfig \
      --output $TALOSCONFIG_FILE \
      $CLUSTER_NAME \
      https://$ENDPOINT:6443

    echo "adding endpoint '${ENDPOINT} configuration to: ${TALOSCONFIG_FILE}"
    talosctl --talosconfig=$TALOSCONFIG_FILE config endpoint $ENDPOINT
  fi
}

function generate_worker() {
  echo "creating: ${WORKER_OUTPUT_DIR}/${NODE_NAME}.yaml"
  talosctl gen config \
    --with-secrets="$SECRETS_FILE" \
    --with-docs=false \
    --with-examples=false \
    --kubernetes-version=$KUBERNETES_VERSION \
    --output-types worker \
    --config-patch-worker @${STRATEGIC_PATCH} \
    --config-patch-worker @${FIREWALL_TEMPLATE} \
    --output ${WORKER_OUTPUT_DIR}/${NODE_NAME}.yaml \
    $EXTRA_ARGS \
    $CLUSTER_NAME \
    https://$ENDPOINT:6443 2>/dev/null
}

###
# parse args
###
EXTRA_ARGS="--force "
while getopts ":t:e:n:c:k:" o; do
    case "${o}" in
        e)
            e=${OPTARG}
            ;;
        n)
            n=${OPTARG}
            ;;
        c)
            c=${OPTARG}
            ;;
        k)
            k=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${n}" ] ; then
  usage
fi

###
# main
###
function generate_patch() {
  mkdir -p $NODE_PATCH_DIR
  ytt \
    -f ${VALUES_DIR}/schema.yml \
    -f $STRATEGIC_PATCH_TEMPLATE \
    -f $JSON_PATCH_TEMPLATE \
    --data-values-file ${VALUES_DIR}/${NODE_NAME}.yaml \
    --output-files ${NODE_PATCH_DIR}

}

# Input
NODE_NAME=$n
if [[ $NODE_NAME =~ control* ]]; then
  NODE_TYPE="control"
elif [[ $NODE_NAME =~ worker* ]]; then
  NODE_TYPE="worker"
else
  echo "Node name must start with 'control' or 'worker'. Got: ${NODE_NAME}"
  exit 1
fi

ENDPOINT=${e:-$DEFAULT_CLUSTER_ENDPOINT} # NOTE: DNS name or IP of the cluster endpoint
CLUSTER_NAME=${c:-$DEFAULT_CLUSTER_NAME}
KUBERNETES_VERSION=${k:-$DEFAULT_KUBERNETES_VERSION}

# These are 'type' (control|worker) specific templates 
STRATEGIC_PATCH_TEMPLATE="${TEMPLATES_DIR}/${NODE_TYPE}/strategic-patch.yaml"
JSON_PATCH_TEMPLATE="${TEMPLATES_DIR}/${NODE_TYPE}/json-patch.yaml"

# These files are generated by ytt
NODE_PATCH_DIR="${PATCHES_DIR}/${NODE_NAME}"
STRATEGIC_PATCH="${NODE_PATCH_DIR}/strategic-patch.yaml"
JSON_PATCH="${NODE_PATCH_DIR}/json-patch.yaml"

generate_patch $NODE_TYPE

if [[ $NODE_TYPE == "control" ]]; then
  generate_controller
else
  generate_worker
fi
